version: '3.8'
services:
  frontend:
    container_name: frontend
    image: frontend:v1

    ports:
      - "9090:80"

    networks:
      - dolat-signal-nw

    depends_on:
      - backend

    restart: "unless-stopped"


  backend:
    container_name: backend
    image: backend:v1

    ports:
      - "5000:5000"

    networks:
      - dolat-signal-nw

    restart: "unless-stopped"


networks:
  dolat-signal-nw:
    driver: bridge
