FROM ubuntu:24.04
WORKDIR /frontend
COPY . . 
LABEL name="Piyush Nandankar"
LABEL email="piyushnandu2@gmail.com"

RUN apt update -y
RUN apt install nginx -y
RUN apt install npm -y
RUN npm install pm2 --global
RUN npm install
RUN npm run build
RUN rm -rf /var/www/html/*
RUN cp -rp dist/* /var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


